# Generated by Django 3.1.2 on 2020-10-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_url',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_resized',
            field=models.ImageField(blank=True, null=True, upload_to='images_resized/'),
        ),
    ]
