# Generated by Django 3.1.2 on 2020-10-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20201007_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image_orig',
            field=models.ImageField(blank=True, null=True, upload_to='images_orig'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_resized',
            field=models.ImageField(blank=True, null=True, upload_to='images_resized'),
        ),
    ]
